[workspace]
resolver = "2"
members = [
    "lib-rs/moss_uikit",
    "lib-rs/moss_ui",

    "platform/core",
    "platform/fs",
    "platform/formation",
    "platform/configuration",
    "platform/user_profile",
    "platform/environment",
    "platform/utl",
    "platform/workspace",

    "view/desktop/bin",

    "view/shared/workbench/tao",
    "view/shared/workbench/service/configuration/common",
    "view/shared/workbench/service/configuration/tao",
    "view/shared/workbench/service/user_profile/tao",
    "view/shared/workbench/service/environment/tao",

    "tools/xtask",
]

# [profile.dev]
# split-debuginfo = "unpacked"
# debug = "limited"
# codegen-units = 16

[profile.release]
debug = "limited"
lto = "thin"
codegen-units = 1


[workspace.dependencies]
moss_hecs = { git = "https://github.com/keenawa-co/moss_hecs.git", branch = "master" }
moss_hecs_hierarchy = { git = "https://github.com/keenawa-co/moss_hecs_hierarchy.git", branch = "main" }

moss_uikit = { path = "lib-rs/moss_uikit" }
moss_ui = { path = "lib-rs/moss_ui" }

platform_core = { path = "platform/core" }
platform_utl = { path = "platform/utl" }
platform_configuration = { path = "platform/configuration" }
platform_formation = { path = "platform/formation" }
platform_user_profile = { path = "platform/user_profile" }
platform_environment = { path = "platform/environment" }
platform_workspace = { path = "platform/workspace" }
platform_fs = { path = "platform/fs" }

workbench_tao = { path = "view/shared/workbench/tao" }
workbench_service_configuration_common = { path = "view/shared/workbench/service/configuration/common" }
workbench_service_configuration_tao = { path = "view/shared/workbench/service/configuration/tao" }
workbench_service_user_profile_tao = { path = "view/shared/workbench/service/user_profile/tao" }
workbench_service_environment_tao = { path = "view/shared/workbench/service/environment/tao" }

tauri = "2.0.0-rc"
specta = "2.0.0-rc.20"
libc = "0.2.155"
fnv = "1.0.7"
anyhow = "1.0"
notify = "6.1.1"
hashbrown = "0.14.5"
arc-swap = "1.7.1"
radix_trie = "0.2.1"
parking_lot = "0.12.3"
derive_more = "0.99.17"
strum = "0.26"
lazy-regex = "3.3.0"
dunce = "1.0.5"
sysinfo = "0.31.2"
tokio = "1"
smol = "2.0.0"
futures = "0.3"
async-task = "4.7.1"
flume = "0.11.0"
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1"
once_cell = "1.19"
lazy_static = "1.4.0"
surrealdb = "1.5.3"
tracing = "0.1"
tracing-subscriber = "0.3.18"
slotmap = "1.0.7"
rustc-hash = "2.0.0"
parking = "2.2.1"
waker-fn = "1.2.0"
im = "15.1.0"
smallvec = "1.13.2"
dyn-clone = "1.0.17"
cargo_metadata = "0.18"
pathdiff = "0.2"
toml = "0.8.19"
spin = "0.9.8"
bencher = "0.1.5"
rand = "0.8.3"
trybuild = "1.0.23"
serde_test = "1.0.117"
ts-rs = "10.0"
